---
title: "Macrophage Figure"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---


```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(reshape2)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(gridExtra)
library(ComplexHeatmap)
library(RColorBrewer)
library(Seurat)
ColorsTreatment<-c("#BD6B73","#CCAD8F","#81C3D7","#16425B")
ColorMacrophageClusters<-brewer.pal(3,"Set1")
ColorPhase<-rev(c("gray",brewer.pal(5,"Pastel2")))

ColorsAllClusters<-c(brewer.pal(8,"Set2"),brewer.pal(3,"Set1"))
library(circlize)
Colors_Feat<-colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))
```

# Preparing Data
```{r Loading}
setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync")
load("5-CellCycle.RData")
DefaultAssay(Macrophages)<-"RNA"
Macrophages<-ScaleData(Macrophages)
Idents(Macrophages)<-"hicat_clusters"
Macrophages$Treatment_New<-recode(Macrophages$Treatment_Broad,
                                 "FUSMB_450_24h_Ipsi"="24h FUS+MB",
                                 "FUSMB_450_72h_Ipsi"="72h FUS+MB")
Macrophages$Treatment_New<-factor(Macrophages$Treatment_New,levels=c(
  "Naive",
  "Sham",
  "24h FUS+MB",
  "72h FUS+MB"))

Macrophages$hicat_clusters<-ordered(Macrophages$hicat_clusters,levels=c("4","1","5"))
Macrophages$clusters_labeled<-recode(Macrophages$hicat_clusters,
                                 "4"="H2-Ab1+",
                                 "1"="Mrc1+",
                                 "5"="F10+")
Macrophages$Phase<-factor(Macrophages$Phase,levels = c("G0","G1S","S","G2M","M","MG1"))

```
# Featureplot
```{r}
Feat<-FeaturePlot(Macrophages,features = c("H2-Ab1","Mrc1","F10","Cd74","Cd163","Trem2"),ncol=1,cols = c("#D3D3D3","red"))&theme(legend.position = "none",
                                                                                                        axis.text = element_blank(),
                                                                                                        axis.title = element_blank(),
                                                                                                        axis.ticks = element_blank())
```


# Clusters UMAP
```{r}
Idents(Macrophages)<-"clusters_labeled"
ColorMacrophageClusters_Labels<-ColorMacrophageClusters
names(ColorMacrophageClusters_Labels)<-levels(Macrophages$clusters_labeled)
Dim1<-DimPlot(Macrophages,group.by = "clusters_labeled",label=FALSE,cols = ColorMacrophageClusters_Labels)+theme(plot.title = element_blank(),
                                                                                                                 axis.ticks = element_blank(),
                                                                                                                 axis.text = element_blank(),
                                                                                                                 legend.text = element_text(size=8),
        legend.key.size = unit(0.1,"mm"),
        legend.spacing = unit(0,"mm"),
        plot.margin = c(0.5,0.5,0.5,0.5,"cm"))+guides(color=guide_legend(override.aes = list(size=4),nrow=1))
```

# Heatmap
```{r}
Idents(Macrophages)<-"clusters_labeled"
markers <- FindAllMarkers(Macrophages, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
Genes2Plot<-markers%>%
    group_by(cluster) %>%
    top_n(n = 30, wt = avg_log2FC)

dot_data<-DotPlot(Macrophages,features=Genes2Plot$gene)
dot_data<-dot_data$data
dot_data<-as.data.frame(pivot_wider(dot_data[,c("id","avg.exp.scaled","features.plot")],names_from = "id",values_from = "avg.exp.scaled"))
rownames(dot_data)<-dot_data$features.plot
dot_data<-dot_data[,-1]
dot_data<-dot_data[,levels(Macrophages$clusters_labeled)]
names(ColorMacrophageClusters)<-levels(Macrophages$clusters_labeled)

Bottom<-columnAnnotation(Cluster=anno_simple(colnames(dot_data),col=ColorMacrophageClusters),show_legend=FALSE,show_annotation_name=FALSE)

HM3<-Heatmap(as.matrix(dot_data),
        cluster_rows = FALSE,
        cluster_columns = FALSE,
        show_row_names = TRUE,
        column_names_rot = 0,
        column_names_side = "top",
        column_names_gp = gpar(fontsize=7),
        column_names_centered = TRUE,
        show_column_names=TRUE,
        row_names_side = "right",
        row_names_gp = gpar(fontsize=7),
        top_annotation = Bottom,
        show_heatmap_legend = FALSE,
        col=Colors_Feat)

HM3_Final<-grid.grabExpr(draw(HM3,padding = unit(c(0.25, 0.75, 0.25, 0.25), "cm")))
```


# Volcano plots
```{r}
Idents(Macrophages)<-"Treatment_New"
clustermarkers72 <- FindMarkers(Macrophages, ident.1 = "72h FUS+MB",ident.2 = "Sham",slot = "scale.data")
th <- theme_bw() + theme(legend.background = element_rect(),
                         plot.title = element_text(angle = 0, size = 10, vjust = 1), 
                                         plot.caption = element_blank(), 
                                         axis.text = element_text(angle = 0,
                                                                  size = 6,
                                                                  vjust = 0.5), legend.position = "none",
                         axis.title = element_text(size=8),
                         panel.grid.major = element_blank())

toptable <- as.data.frame(clustermarkers72)
toptable$lab <- rownames(clustermarkers72)

Genes<-c("Ifitm3","Ms4a4c","Vim","C1qa","Fcrls","Csf1r","Pf4","Siglech","Tgfbi","Oasl1","Lgals3","Mrc1","Mertk","Hexb","Ccr1","Cxcl10","Ly6a")
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable$xvals <- toptable[['avg_diff']]
toptable$yvals <- -log10(toptable[['p_val_adj']])

xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))


Volcano72 <- ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(color=ColorsTreatment[4],na.rm = TRUE,size=0.1)+ labs(title = '72h FUS+MB vs Sham')+xlab(xlab) + ylab(ylab) + geom_label_repel(aes(label=lab),size=3,label.padding = unit(0.1, "lines"))+theme(panel.grid = element_blank())
```


# barcharts
```{r}
df<-as.data.frame(table(Macrophages$clusters_labeled,Macrophages$Treatment_New))
df$Cluster<-df$Var1
df$Treatment<-df$Var2
levels(df$Treatment)<-c("Naive","Sham","24h FUS+MB","72h FUS+MB")
BC2<-ggplot(df, aes(y=Cluster,x=Freq,fill=Treatment)) + 
  scale_fill_manual(values = ColorsTreatment,guide=guide_legend(nrow=2)) + 
  geom_bar(position="fill",stat="identity") + 
  geom_tile(aes(y=Cluster,x=0),fill=ColorMacrophageClusters[df$Var1],width=0.05) + 
  theme_minimal() + 
  scale_x_continuous(breaks = c(0,0.5,1),labels=c("0%","50%","100%"),expand = c(0,0)) +
  theme(legend.position="top",
        axis.title = element_blank(),
        plot.margin=margin(0,0.5,0.5,0.5,"cm"),
        panel.grid.major.y = element_blank(),
        axis.text = element_text(size=6,hjust=1,family = "Arial"),
        legend.title = element_blank(),
        legend.text = element_text(size=8,family="Arial"),
        legend.key.size = unit(0.5,"line"),
        legend.spacing = unit(0.1,"line"))



df<-as.data.frame(table(Macrophages$clusters_labeled,Macrophages$Phase))
df$Cluster<-df$Var1
df$Phase<-df$Var2

BC3<-ggplot(df, aes(y=Cluster,x=Freq,fill=Phase)) + 
  scale_fill_manual(values = rev(ColorPhase),guide=guide_legend(nrow=2)) + 
  geom_bar(position="fill",stat="identity") + 
  geom_tile(aes(y=Cluster,x=0),fill=ColorMacrophageClusters[df$Var1],width=0.05) + 
  theme_minimal() + 
  scale_x_continuous(breaks = c(0,0.5,1),labels=c("0%","50%","100%"),expand = c(0,0)) +
  theme(legend.position="top",
        axis.title = element_blank(),
        plot.margin=margin(0,0.5,0.5,0.5,"cm"),
        panel.grid.major.y = element_blank(),
        axis.text = element_text(size=6,hjust=1,family = "Arial"),
        legend.title = element_blank(),
        legend.text = element_text(size=8,family="Arial"),
        legend.key.size = unit(0.5,"line"),
        legend.spacing = unit(0.1,"line"))
```

# Ontology
```{r}
library(topGO)
setwd("/Users/alinakline-schoder/Documents/Papers/MicrogliaPaper-Joint/FUSMicroglia/2021-JointPaper/ImportantFiles/")
source('Ontology.R')
library(org.Mm.eg.db)

clustermarkers72_filt<-clustermarkers72[clustermarkers72$p_val_adj<0.05,]
clustermarkers72_filt<-clustermarkers72_filt[clustermarkers72_filt$avg_diff>1,]

Onto<-GO_Search(Macrophages,clustermarkers72_filt)
Onto$PCT<-Onto$Significant/Onto$Annotated*100
Onto<-Onto[Onto$Annotated>10,]


Terms<-c("regulation of response to cytokine stimulus",
         "response to interferon-gamma",
         "cellular response to interleukin-1",
         "innate immune response",
         "immune response",
         "defense response",
         "extracellular exosome")

KSLab<-bquote(~-Log[10] ~ italic(P[KS]))
FisLab<-bquote(~-Log[10] ~ italic(P[Fis]))
Onto_Filtered<-Onto[Onto$Term %in% Terms,]
OntPlot<-ggplot(Onto_Filtered,
                aes(y=Term,
                    x=-log(PVal_Fis),
                    color=-log(PVal_KS),size=PCT))+
  geom_point(na.rm = FALSE)+ scale_size_continuous(limits = c(7,24),breaks = c(10,20),guide=guide_legend(title="Genes (%)",title.position = "top"))+
  theme_minimal()+
  theme(legend.title = element_text(size=6),
        legend.text = element_text(size=6),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size=8),
        axis.text = element_text(size=8),
        legend.position="bottom",
        legend.box = "horizontal",
        legend.key.height = unit(1,"mm"),
        legend.key.size = unit(3,"mm"),
        legend.spacing = unit(0,"mm"),
        plot.margin = margin(0.5,0.5,0,0,"cm"),
        legend.box.spacing = margin(-0.1,0,0,0,"cm"))+xlab(FisLab)+xlim(0,10)+scale_color_gradient(low="#0E0028",high="#9A63FF",guide=guide_colorbar(title=KSLab,title.position = "top"))
```
# Highlighting on master umap
```{r}
setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync")
load("4-Clustered-All.RData")
Integrated$Treatment_New<-recode(Integrated$Treatment_Broad,
                                 "FUSMB_450_24h_Ipsi"="24h FUS+MB",
                                 "FUSMB_450_72h_Ipsi"="72h FUS+MB")
Integrated$Treatment_New<-factor(Integrated$Treatment_New,levels=c("Naive","Sham","24h FUS+MB","72h FUS+MB"))

Integrated$cell_number<-recode(Integrated$cell_type,
                             "Neutrophils"="0",
                             "Microglia 1"="1",
                             "Microglia 2"="2",
                             "Microglia 3"="3",
                             "Macrophages 1"="4",
                             "Macrophages 2"="5",
                             "Macrophages 3"="6")
Integrated$cell_number<-ordered(Integrated$cell_number,levels=c("0","1","2","3","4","5","6"))
ColorsAllClusters<-c("gray","gray","gray","gray","#C59797","#A6D854","#FFD92F")

Highlight<-DimPlot(Integrated,group.by = "cell_number",cols=ColorsAllClusters,label=FALSE)+NoLegend()+
  theme(plot.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        panel.border=element_rect(size=0.5,colour = "black",fill=NA))
```
# Pie chart
```{r}
df<-data.frame(table(Macrophages$Treatment_New))
Norm<-data.frame(table(Integrated$Treatment_New))
df$Freq_Norm<-df$Freq/Norm[df$Var1,]$Freq
Pie<-ggplot(df, aes(x=Var1, y=Freq_Norm, fill=Var1)) +
  geom_bar(stat="identity", width=1) + scale_fill_manual(values=ColorsTreatment,guide=guide_legend(nrow=2)) +
  scale_y_continuous(limits = c(0,0.65),breaks = c(0,0.25,0.5),labels=c("0%","25%","50%"),expand = c(0,0),position = "right")+theme_minimal()+
  theme(legend.position=c(0.5,0.95),
        plot.margin=margin(0.5,0.5,0.5,0.5,"cm"),
        legend.title = element_blank(),
        legend.text = element_text(size=8),
        legend.key.size = unit(0.75,"line"),
        axis.line.x = element_line(size=0.1),
        axis.text.x = element_blank(),
        axis.title.y = element_blank()) + 
  ylab("Macrophages (% of Total Cells)") + 
  xlab("Treatment")
```

# Putting it together
```{r}
Inset<-ggdraw(Dim1 + ylim(-9.5,7.51)+theme_half_open(12) + theme(plot.title = element_blank(),axis.ticks = element_blank(),axis.text = element_blank(),legend.position = c(0,0.1))) +
  draw_plot(Highlight, .625, .625, .375, .375) +
  draw_plot_label(
    c("B"),
    c(0.66),
    c(0.75),
    size = 12)

BCs<-plot_grid(BC2,BC3,nrow=2,align = "v",labels = c("D","E"))
A<-plot_grid(Inset,Pie,nrow=1,align = "h",axis = "t",labels = c("A","C"))
Top<-plot_grid(A,BCs,nrow=1,rel_widths = c(1.75,0.75),align = "h",axis = "b")
A<-plot_grid(Volcano72,OntPlot,nrow=2,labels = c("H","I"),rel_widths = c(1.5,1))
B<-plot_grid(HM3_Final,Feat,A,nrow=1,rel_widths = c(0.5,0.35,1),labels = c("F","G"))

Full<-plot_grid(Top,B,nrow=2,rel_heights = c(0.75,2))

setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync")
ggsave("Macrophages.png",width = 8.5,height = 11,units = "in",bg="white")
```


