---
title: "Calculating Concentrations"
author: "Alina Kline-Schoder"
date: "9/30/2020"
output: pdf_document
---

```{r setup, include=FALSE}
remove(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rstatix)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(viridis)
library(Seurat)
library(RColorBrewer)
setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync")
load("5-IntegratedMicroglia.RData")
Microglia$Treatment_New<-recode(Microglia$Treatment_Broad,
                                 "FUSMB_450_24h_Ipsi"="24h FUS+MB",
                                 "FUSMB_450_72h_Ipsi"="72h FUS+MB")
Microglia$Treatment_New<-ordered(Microglia$Treatment_New,levels=c("Naive","Sham","24h FUS+MB","72h FUS+MB"))
ColorsTreatment<-c("#BD6B73","#CCAD8F","#81C3D7","#16425B")
names(ColorsTreatment)<-levels(Microglia$Treatment_New)
Colorssub<-unname(ColorsTreatment[c("24h FUS+MB","72h FUS+MB")])
temp<-rowMeans(col2rgb(Colorssub))
library(circlize)
```

```{r cars}
setwd("/Users/alinakline-schoder/Documents/Papers/MicrogliaPaper-Solo/Infiltration/InfiltrationData/")
FACS<-read.csv('AllData-Table 1.csv')
FACS<-FACS[,c("Group","Phagocytes","Cavitation2","ICD","SCD.uh","SCD.h")]
FACS<-na.omit(FACS)
FACS<-separate(FACS,"Group",sep="_",into=c("Time","Treatment"),remove=FALSE)
FACS<-na.omit(FACS)
FACS<-FACS[FACS$Treatment=="FUS/MB",]
FACS<-FACS[,c("ICD","SCD.uh","SCD.h")]
colnames(FACS)<-c("ICD","SCDuh","SCDh")
FACS$Pressure<-450

Colors_FUS_Group_Broad<-c(ColorsTreatment[1],ColorsTreatment[2],Colorssub)
```


```{r}
setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync/InfiltrationData/")
FACS<-read.csv('AllData-Table 1.csv')
FACS<-FACS[,c("Group","Phagocytes","Cavitation2","ICD","SCD.uh","SCD.h")]
FACS<-na.omit(FACS)
FACS<-separate(FACS,"Group",sep="_",into=c("Time","Treatment"),remove=FALSE)
FACS<-na.omit(FACS)

FACS$Time<-as.numeric(FACS$Time)
FACS$Treatment<-as.factor(FACS$Treatment)
FACS$Group<-as.factor(FACS$Group)
FACS$Phagocytes<-as.numeric(FACS$Phagocytes)
df <- FACS
TextSize=3
df$Treatment_Broad<-df$Treatment
levels(df$Treatment_Broad)<-c("Control","Sham","FUS/MB","Sham")
df$Treatment<-ordered(df$Treatment,levels=c("Control","MB","FUS","FUS/MB"))
df$Time<-factor(df$Time)
df$Time<-recode(df$Time,"0"="Control",
                          "24"="24h",
                          "120"="5d",
                          "72"="72h",
                          "672"="4wk")

df<-df[df$Treatment=="FUS/MB",]


library(ggpmisc)
b<-ggplot(df,aes(x=SCD.h,y=Phagocytes))+geom_point()+facet_grid(Time~.)+geom_smooth(method="lm",se = FALSE,fullrange=TRUE,color="black",size=0.5) + stat_fit_glance(method = "lm",
                  method.args = list(formula = y ~ x),label.y = 0.95,label.x=0.1,
                  mapping = aes(label = paste(expression(paste(R^2)),sprintf('~"="~%.2g', stat(r.squared)))),show.legend = TRUE, parse = TRUE,vstep = 0.1,size=TextSize)+ stat_fit_glance(method = "lm",
                  method.args = list(formula = y ~ x),label.y = 0.8,label.x=0.1,
                  mapping = aes(label = sprintf('P~"="~%.2g', stat(p.value))),show.legend = TRUE, parse = TRUE,vstep = 0.1,size=TextSize)+theme_bw()+theme(legend.position = "none",
                                                                                                                                                           plot.margin = margin(0.25,0.25,0.25,0.25,unit = "cm"),
                                                                                                                                                           axis.title = element_text(size=12,hjust=0.5))+ylab("Normalized Brain Macrophage Cell Count") + ylim(0,15)+xlim(-5,45)+geom_point()+xlab("SCDh (dB)")
```


```{r}

Idents(Microglia)<-"orig.ident"
Microglia<-subset(Microglia,idents = c("Run1","Run2","Run3"))
Idents(Microglia)<-"Treatment_New"
Microglia<-subset(Microglia,idents = c("Sham"),invert=TRUE)

Microglia$Cav<-factor(paste(Microglia$orig.ident,Microglia$FUS_Group_Broad))
Microglia$SCDH<-as.numeric(as.character(recode(Microglia$Cav,
                                               "Run1 FUS/MB_24"=16.3,
                                               "Run1 FUS/MB_72"=94.4,
                                               "Run2 FUS/MB_24"=24.8,
                                               "Run2 FUS/MB_72"=82.7,
                                               "Run3 FUS/MB_72"=33.3,
                                               "Run1 Control"=0,
                                               "Run2 Control"=0,
                                               "Run3 Control"=0)))

Idents(Microglia)<-"SCDH"
```

```{r}
setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync/InfiltrationData/")
FACS<-read.csv('AllData-Table 1.csv')
FACS<-FACS[,c("Group","Phagocytes","Cavitation2","ICD","SCD.uh","SCD.h")]
FACS<-na.omit(FACS)
FACS<-separate(FACS,"Group",sep="_",into=c("Time","Treatment"),remove=FALSE)
FACS<-na.omit(FACS)
a<-dim(FACS)
FACS$obs<-1:as.numeric(a[1])
FACS$Time<-as.numeric(FACS$Time)
FACS$Treatment<-as.factor(FACS$Treatment)
FACS$Group<-as.factor(FACS$Group)
FACS$Phagocytes<-as.numeric(FACS$Phagocytes)
df <- FACS

df$Treatment_Broad<-df$Treatment
levels(df$Treatment_Broad)<-c("Control","Sham","FUS/MB","Sham")
df$Treatment<-ordered(df$Treatment,levels=c("Control","MB","FUS","FUS/MB"))
df$Time<-factor(df$Time)
df$Time<-recode(df$Time,
                "0"="Control")

# Boxplot
df$Group_Broad<-df$Group
levels(df$Group_Broad)<-c("0_Control","120_Sham","120_FUS/MB","120_Sham","24_Sham","24_FUS/MB","24_MB","672_Sham","672_FUS/MB","672_Sham","72_Sham","72_FUS/MB","72_Sham","0_Control")

#Add in stats
stats <- df %>%
  pairwise_t_test(Phagocytes ~ Group_Broad,p.adjust.method = "holm") %>%
  add_significance("p.adj") %>%
  separate(group1,sep="_",into=c("Time1","Treatment1"),remove=FALSE) %>%
  separate(group2,sep="_",into=c("Time2","Treatment2"),remove=FALSE) %>%
  mutate(Treatment=Treatment1) %>%
  mutate(Time=Time1)

New<-as.data.frame(x=c("0_Control","24_Sham","24_FUS/MB","72_Sham","72_FUS/MB","120_Sham","120_FUS/MB","672_Sham","672_FUS/MB"))
New$Val<-c(1,1.8,2.2,2.8,3.2,3.8,4.2,4.8,5.2)
colnames(New)<-c("group2","Val")
Control1<-stats[stats$Treatment1=="Control",]
Control2<-stats[stats$Treatment2=="Control",]
Control<-rbind(Control1,Control2)
Control$xmin=1
Control<-left_join(Control,New,by="group2")
Control$xmax=Control$Val
Control$Treatment=Control$Treatment2
SameTime<-stats[stats$Time1==stats$Time2,]
colnames(New)<-c("group2","Val")
SameTime<-left_join(SameTime,New,by="group2")
colnames(New)<-c("group1","Val")
SameTime<-left_join(SameTime,New,by="group1")
SameTime$xmin=SameTime$Val.x
SameTime$xmax=SameTime$Val.y
SameTime$Treatment=NA
SameTreatment<-stats[stats$Treatment1==stats$Treatment2,]
colnames(New)<-c("group2","Val")
SameTreatment<-left_join(SameTreatment,New,by="group2")
colnames(New)<-c("group1","Val")
SameTreatment<-left_join(SameTreatment,New,by="group1")
SameTreatment$xmin=SameTreatment$Val.x
SameTreatment$xmax=SameTreatment$Val.y
SameTreatmentFinal<-SameTreatment[,c("Treatment","group1","group2","p.adj.signif","xmin","xmax","p.adj")]
ControlFinal<-Control[,c("Treatment","group1","group2","p.adj.signif","xmin","xmax","p.adj")]
SameTimeFinal<-SameTime[,c("Treatment","group1","group2","p.adj.signif","xmin","xmax","p.adj")]
AllStats<-rbind(SameTimeFinal,SameTreatmentFinal,ControlFinal)

df$Treatment<-recode(df$Treatment,"Control"="Naive")
df$Treatment_Broad<-recode(df$Treatment_Broad,"Control"="Naive")
df$Treatment_Broad<-recode(df$Treatment_Broad,"FUS/MB"="FUS+MB")
df$Treatment<-recode(df$Treatment,"FUS/MB"="FUS+MB")
df$Treatment<-recode(df$Treatment,"MB"="MB Sham")
df$Treatment<-recode(df$Treatment,"FUS"="FUS Sham")
df$Time<-recode(df$Time,"Control"="Naive",
                "120"="5d",
                "672"="4wk",
                "72"="72h",
                "24"="24h")
Colors_FUS_Group_Broad<-unname(Colors_FUS_Group_Broad)
Flow<-ggplot(df, aes(x = Time, y = Phagocytes))+
  geom_boxplot(aes(color=Treatment_Broad),fill="white",show.legend = FALSE) + 
  scale_color_manual(values = c("black","black","black")) + geom_point(aes(group=Treatment_Broad,fill=Treatment_Broad,shape=Treatment),
                                                                       position=position_dodge(width=0.75),size=2) + 
  xlab("Sacrifice Time") + 
  ylab("Normalized Brain Macrophage Cell Count") + 
  theme_bw() + 
  scale_fill_manual(values = Colors_FUS_Group_Broad[1:3]) + 
  scale_shape_manual(values=c(21, 24, 25,23)) + 
  guides(shape = guide_legend(title.position = "top",title.hjust = 0.5,override.aes = list(shape = c(21, 24, 25,23), fill = c(Colors_FUS_Group_Broad[1],Colors_FUS_Group_Broad[2],Colors_FUS_Group_Broad[2],Colors_FUS_Group_Broad[3])),nrow = 1),fill="none") + 
  stat_pvalue_manual(AllStats,y.position = 15,hide.ns = TRUE,xmin="xmin",xmax="xmax",step.increase = 0.1,color="black",label = "p.adj.signif",size=5,label.size = 5) + 
  ylim(0,25) + 
  theme(legend.text = element_text(size=8),
        legend.title = element_blank(),
        axis.title = element_text(size=12),
        axis.text = element_text(size=10),
        legend.position = "top",
        legend.background = element_blank(),
        plot.margin = margin(0.25,0.25,0.25,0.5,"cm"),
        panel.spacing = unit(0,"mm"),
        legend.key.size = unit(0.1,"cm"),
        legend.margin = margin(0,0,0,0,"cm"))
```

# Showing values across flow
```{r}
setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync/InfiltrationData/")
FACS<-read.csv('AllData-Table 1.csv')
FACS<-FACS[,c("Group","Phagocytes","Cavitation2","ICD","SCD.uh","SCD.h")]
FACS<-na.omit(FACS)
FACS<-separate(FACS,"Group",sep="_",into=c("Time","Treatment"),remove=FALSE)
FACS<-na.omit(FACS)

FACS$Time<-as.numeric(FACS$Time)
FACS$Treatment<-as.factor(FACS$Treatment)
FACS$Group<-as.factor(FACS$Group)
FACS$Phagocytes<-as.numeric(FACS$Phagocytes)
df <- FACS
TextSize=3
df$Treatment_Broad<-df$Treatment
levels(df$Treatment_Broad)<-c("Control","Sham","FUS/MB","Sham")
df$Treatment<-ordered(df$Treatment,levels=c("Control","MB","FUS","FUS/MB"))
df$Time<-factor(df$Time)
df$Time<-recode(df$Time,"0"="Control",
                          "24"="24h",
                          "120"="5d",
                          "72"="72h",
                          "672"="4wk")

df<-df[df$Treatment=="FUS/MB",]
dfexp<-df[df$Treatment=="FUS/MB",]
colnames(dfexp)<-c("Group","Time","Treatment","Phagocytes","Cavitation2","ICD","SCDuh","SCDh","Treatment_Broad")
dfexp<-pivot_longer(dfexp,cols = c("ICD","SCDuh","SCDh"))
dfexp$name<-factor(dfexp$name,levels=c("SCDh","SCDuh","ICD"))
c<-ggplot(dfexp,aes(x=Time,y=value))+geom_boxplot()+geom_point()+facet_wrap(name~.,ncol=1)+theme_bw()+ylab("dB")+ylim(-5,45)+theme(legend.position = "none")+xlab("Sacrifice Time")
```

#Putting it together
```{r}
library(cowplot)

A<-plot_grid(Flow,nrow=1,labels = c("A"))
BC<-plot_grid(c,b,nrow=1,align = "h",axis = "tb",rel_widths = c(0.5,0.75),labels = c("B","C"))

full<-plot_grid(A,BC,nrow=1,rel_widths = c(1,1.5))
setwd("/Users/alinakline-schoder/Desktop/RDatas.nosync")
ggsave("Cavitation.png",width = 8.5,height = 5,units = "in",plot = full)
```

