---
title: "Figure 2"
author: Alina Kline-Schoder
date: | 
      | Started on 06/01/2021
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  github_document:
    toc: yes
---
# Figure 3 - Microglia Clustering and DAM

```{r message = FALSE, echo = FALSE}
rm(list = ls())
library(cowplot)
library(Seurat)
require(ggdendro)
require(Rmisc)
library(Matrix)
library(MASS)
library(xtable)
library(Matrix.utils)
library(reshape2)
library(BiocManager)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(tidyverse)
library(ggsignif)
library(broom)
library(rstatix)
library(ggpmisc)
library(gridExtra)
library(here)
library(circlize)
library(sjmisc)
#setwd("F:/Data/Sequencing/SavedData")
setwd("/Users/alinakline-schoder/Documents/Github.nosync/Data")
load("3-AllCells.RData")
load("5-MicrogliaFigures.RData")
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))

th <- theme_bw() + theme(legend.background = element_rect(),
                         plot.title = element_text(angle = 0, size = 10, vjust = 1), 
                                         plot.caption = element_blank(), 
                                         axis.text = element_text(angle = 0,
                                                                  size = 6,
                                                                  vjust = 0.5), legend.position = "none",
                         axis.title = element_text(size=8),
                         panel.grid.major = element_blank())
ColorsAllClusters<-c("#66C2A5","#FC8D62","#8DA0CB","#E78AC3","#C59797","#A6D854","#FFD92F","#BA95C7","#D3D942","#FFD92F","#B1A884","#BA95C7")
ColorsAllClusters[!str_contains("Microglia",levels(Integrated$cluster_full),switch = T)]<-"gray"
ColorsAllClusters[str_contains("Microglia",levels(Integrated$cluster_full),switch = T)]<-"red"

ColorsTreatment<-c("#FFFFFF","#A3A3A3","#75A0B2","#205F83")
col_fun = colorRamp2(c(-2, 0, 2), c("blue", "#D3D3D3", "red"))
```

# Microglia Highlighted
```{r}
Idents(Integrated)<-"cluster_full"
Highlight<-DimPlot(Integrated,group.by = "cluster_full",cols=ColorsAllClusters,label=FALSE)+NoLegend()+
  theme(plot.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(0,0,0,0,"cm"),
        panel.spacing = unit(0,"cm"))
```

# Clusters UMAP
```{r}
Dim1<-DimPlot(Microglia,group.by = "clusters_labeled",label=FALSE,cols = ColorMacrophageClusters)+theme(plot.title = element_blank(),
                                                                                                                 axis.ticks = element_blank(),
                                                                                                                 axis.text = element_blank(),
                                                                                                                 legend.text = element_text(size=8),
        legend.key.size = unit(0.1,"mm"),
        legend.spacing = unit(0,"mm"),
        legend.position = c(0.3,1))+guides(color=guide_legend(override.aes = list(size=4),nrow=1))+scale_y_continuous(limits=c(-6.5,5))+scale_x_continuous(limits=c(-5,7))
```

# volcano 
```{r}
toptable <- as.data.frame(DAMMarkers)
toptable$lab <- rownames(DAMMarkers)
Genes<-c("Cd9","Lpl","Csf1","Spp1","Cst7","Apoe","Axl","Tmem119","P2ry12","Ctsb","Ctsz","Selplg","Cd63","Pnck","Clmp","Ccr6","Trem2")
toptable[!(toptable$lab %in% Genes),]$lab<-NA
toptable[toptable$p_val_adj>0.05,]$lab<-NA
toptable[abs(toptable$avg_log2FC)<1,]$lab<-NA
toptable$xvals <- toptable[['avg_log2FC']]
toptable$yvals <- -log10(toptable[['p_val_adj']])
xlab<-bquote(~Log[2] ~ "fold change")
ylab<-bquote(~-Log[10] ~ italic(P))
ggplot(toptable, aes(x = xvals, y = yvals)) + th + geom_point(na.rm = TRUE,size=0.1) + labs(title = '1d BBBO v Sham')+xlab(xlab) + ylab(ylab) + geom_label_repel(aes(label=lab),size=3,label.padding = unit(0.1, "lines"),max.overlaps = 20)+theme(panel.grid = element_blank())
```

# percentage of microglia
```{r}
tab<-as.data.frame(table(Microglia$orig.ident,Microglia$Treatment,Microglia$seurat_clusters))
tab<-tab[tab$Var3=="2",]
Tota<-as.data.frame(table(Microglia$orig.ident,Microglia$Treatment))
Tota$Full<-paste(Tota$Var1,Tota$Var2)
tab$Full<-paste(tab$Var1,tab$Var2)
rownames(Tota)<-Tota$Full

tab$Freq_Adj<-tab$Freq/Tota[tab$Full,]$Freq
tab[tab$Freq==0,]$Freq_Adj<-0
tab<-tab[tab$Full!="EA001 Naive",]
tab<-tab[tab$Full!="EA001 1d BBBO",]
tab<-tab[tab$Full!="EA001 3d BBBO",]

tab<-tab[tab$Full!="EA002 Naive",]
tab<-tab[tab$Full!="EA002 Sham",]
tab<-tab[tab$Full!="EA002 3d BBBO",]
tab<-tab[tab$Full!="EA005 1d BBBO",]

ggplot(tab,aes(x=Var2,y=Freq_Adj))+geom_point()+scale_y_continuous(limits=c(0,1))+stat_compare_means(method = "anova")
```


# Heatmap of DEG within DAM
```{r}
Idents(DAM)<-"Treatment"
marks<-DAM_markers_treatment
marks$gene<-rownames(marks)
marks <- marks[marks$p_val_adj<0.05,]
marks$pct.dif<-marks$pct.1-marks$pct.2
marks_SN<-marks[marks$cluster!="Naive"&marks$cluster!="Sham",]
Genes2Plot<-marks_SN%>%
    group_by(cluster) %>%
    top_n(n = 10, wt = pct.dif)
Genes2Plot<-unique(Genes2Plot$gene)
Data<-t(DAM@assays$RNA@data[Genes2Plot,])
Data<-cbind(as.data.frame(Data),DAM$Treatment)
colnames(Data)[dim(Data)[2]]<-"Treatment"
Data<-Data[order(Data$Treatment),]
Treatment<-Data$Treatment
Data<-Data[,1:(dim(Data)[2]-1)]
Data<-Seurat::ScaleData(t(as.matrix(Data)))
names(ColorsTreatment)<-levels(DAM$Treatment)
Top<-columnAnnotation(Treatment=anno_simple(Treatment,height = unit(2, "mm"),col = ColorsTreatment,border = TRUE),show_legend=FALSE,show_annotation_name=FALSE)
Heatmap(Data,
            cluster_rows = FALSE,
            cluster_columns = FALSE,
            show_row_names = TRUE,
            show_column_names = FALSE,
            row_names_side = "left",
            top_annotation = Top,
            col=col_fun,
            show_heatmap_legend = FALSE,
            row_names_gp = gpar(fontsize=6,family="Arial"),
            column_split = Treatment,
            column_title_gp = gpar(fontsize=8,family="Arial"))
```

# Ontology searches
```{r}
Onto_1d<-GO_Search(sub2,marks_1d)
Onto_1d$PCT<-(Onto_1d$Significant/Onto_1d$Annotated)*100
Onto_1d<-Onto_1d[Onto_1d$Annotated>10,]
Onto_1d<-Onto_1d[Onto_1d$Significant>1,]

Onto_3d<-GO_Search(sub2,marks_3d)
Onto_3d$PCT<-(Onto_3d$Significant/Onto_3d$Annotated)*100
Onto_3d<-Onto_3d[Onto_3d$Annotated>10,]
Onto_3d<-Onto_3d[Onto_3d$Significant>1,]
```

# DAM gene dotplot
```{r}
DAMMarkers<-c('Cst3', 'Hexb', 'Lpl', 'Cst7', 'Apoe', 'Ctsd', 'Tyrobp', 'Trem2', 'Cd9', 'Itgax', 'Cd63', 'Timp2')

DotPlot(Microglia,group.by = "seurat_clusters",features=DAMMarkers)
```


# Putting it all together
```{r}
Inset<-ggdraw(Dim1 + theme_half_open(12) + theme(plot.title = element_blank(),axis.ticks = element_blank(),axis.text = element_blank(),legend.position = c(0,0.1))) +
  draw_plot(Highlight, .7, .7, .3, .3) +
  draw_plot_label(
    c("b"),
    c(0.75),
    c(0.985),
    size = 12)
```

